export default function generateHeader(): string {
  const result = [];
  result.push(`// generated by ts-bicycle`);
  result.push(`// do not edit by hand`);
  result.push(``);
  return result.join('\n');
}
